"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var auth_1 = require("../controllers/auth");
var token_1 = require("../middleware/token");
var user_1 = require("../controllers/user");
var router = express.Router();
router.post('/join', auth_1.join, token_1.createToken);
router.post('/login', auth_1.login, token_1.createToken);
router.delete('/logout', token_1.verifyToken, auth_1.logout);
router.post('/naver', auth_1.getNaverUserInfo, auth_1.joinSocialUser, token_1.createToken);
router.post('/google', auth_1.getGoogleUserInfo, token_1.createToken);
router.get('/token/refresh', token_1.renewToken);
router.get('/token/verify', token_1.verifyToken, user_1.getUserProfile);
exports.default = router;
