"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var group_1 = require("../controllers/group");
var router = express.Router();
router.get('/', group_1.getGroupList);
router.post('/', group_1.createGroup);
router.delete('/:id', group_1.deleteGroup);
router.patch('/:id', group_1.patchGroup);
router.post('/calendar', group_1.postGroupSchedule);
router.put('/calendar/:id', group_1.putGroupSchedule);
router.delete('/calendar/:id', group_1.deleteGroupSchedule);
router.get('/:id/calendar', group_1.getGroupSchedule);
router.post('/:group_id/invite-link', group_1.postInviteLink);
router.get('/invite-link/:inviteCode', group_1.getInvitation);
router.post('/join/:inviteCode', group_1.postGroupJoin);
exports.default = router;
