"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var token_1 = require("../middleware/token");
var user_1 = require("../controllers/user");
var calendar_1 = require("../controllers/calendar");
var group_1 = require("../controllers/group");
var router = express.Router();
router.patch('/profile', user_1.patchUserProfile, token_1.createToken);
router.patch('/profile/password', user_1.patchUserPassword);
router.put('/calendar/:id', user_1.putUserSchedule);
router.get('/calendar', user_1.getUserPersonalSchedule);
router.post('/calendar', calendar_1.postPersonalSchedule);
router.delete('/group/:id', group_1.deleteGroupUser);
router.delete('/calendar/:id', calendar_1.deletePersonalSchedule);
exports.default = router;
