name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DB_DATABASE: testdb
  DB_USER: root
  DB_PASSWORD: root

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up MySQL
        run: |
          echo "Set up MySQL"
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Install dependencies
        run: |
          echo "Install Dependencies"
          cp .env.sample .env
          npm install
      - name: Run tests
        run: npm run test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
